// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5a-3KUgOAnyFBqL3Trx444OQE_wc7XJs',
    appId: '1:518889647428:web:1c9563c074a64cbb65fb11',
    messagingSenderId: '518889647428',
    projectId: 'mafia-982c0',
    authDomain: 'mafia-982c0.firebaseapp.com',
    storageBucket: 'mafia-982c0.firebasestorage.app',
    measurementId: 'G-XL9VCB3LWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Fmgye6dd4zDggP0JUBRaPOBtAogFDXs',
    appId: '1:518889647428:android:21c6a19442c53b0965fb11',
    messagingSenderId: '518889647428',
    projectId: 'mafia-982c0',
    storageBucket: 'mafia-982c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6HqC07sVCtmCza_SRyAyOTkULuxsN4XU',
    appId: '1:518889647428:ios:12ec23b740ea4e9665fb11',
    messagingSenderId: '518889647428',
    projectId: 'mafia-982c0',
    storageBucket: 'mafia-982c0.firebasestorage.app',
    iosBundleId: 'com.example.mafiaGame.RunnerTests',
  );
}
