// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTn32Wwq-4KleKTwYMKtbvXZ94ecxOu2k',
    appId: '1:657753752065:web:72df4e559268c7cf617600',
    messagingSenderId: '657753752065',
    projectId: 'mafia-game-b1ed8',
    authDomain: 'mafia-game-b1ed8.firebaseapp.com',
    storageBucket: 'mafia-game-b1ed8.firebasestorage.app',
    measurementId: 'G-HQWRB835VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiFlve1ydHI6Gf3iUYn3p2IxEHUZyUq6E',
    appId: '1:657753752065:android:dd2e3aed68147476617600',
    messagingSenderId: '657753752065',
    projectId: 'mafia-game-b1ed8',
    storageBucket: 'mafia-game-b1ed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydn30lZN7sx70MP5oKj3Dny3QfxsO8fQ',
    appId: '1:657753752065:ios:fecdbb50529da4bc617600',
    messagingSenderId: '657753752065',
    projectId: 'mafia-game-b1ed8',
    storageBucket: 'mafia-game-b1ed8.firebasestorage.app',
    iosBundleId: 'com.example.mafiaGame',
  );
}
